// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "VedaAI",
    platforms: [
        .iOS("26.0")
    ],
    products: [
        .iOSApplication(
            name: "VedaAI",
            targets: ["AppModule"],
            bundleIdentifier: "app.VedaAI",
            teamIdentifier: "TZTPF27ABB",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.yellow),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            urlSchemes: ["vedaai"],
            capabilities: [
                .microphone(purposeString: "This app uses the microphone to capture your voice for AI interactions."),
                .camera(purposeString: "This app uses the camera to capture images for AI analysis."),
                .fileAccess(.pictureFolder, mode: .readWrite),
                .speechRecognition(purposeString: "This app uses speech recognition to convert your voice into text for AI processing.")
                .siri()
            ],
            appCategory: .education
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ],
    swiftLanguageVersions: [.version("6")]
)
